In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('reactive_input.csv')
df.head(3)

,CustomerID,Name,Email,Phone,Lapse_Propensity,Customer_Lifetime_Value,Call_Agent,Discount_Eligibility,Annual_Premium
0,1,John Doe,johndoe@example.com,123-456-7890,0.25,1500,Agent A,eligible,1000
1,2,Jane Smith,janesmith@example.com,987-654-3210,0.35,1200,Agent B,eligible,1100
2,3,Alice Johnson,alicejohnson@example.com,456-789-0123,0.15,800,Agent C,not eligible,1050

In [29]:
from faker import Faker
import random
import pandas as pd

# Initialize Faker
fake = Faker()

def generate_customer():
    name = fake.name()
    email = fake.email()
    phone_number = fake.phone_number()
    return {
        'Name': name,
        'Email': email,
        'Phone': phone_number,
        'Lapse_Propensity': round(random.random(),2),
        'Customer_Lifetime_Value': round(random.uniform(-5000, 50000),2),
        'Call_Agent': name,
        'Discount_Eligibility': random.choice(['eligible', 'not eligible']),
        'Age': random.randint(18, 70),
        'Tenure': random.randint(1, 20),
        'Family_Status': random.choice(['Single', 'Couple', 'Single parent family', 'Family', 'Family with Multiple Children']),
        'Annual_Premium': round(random.uniform(1000, 10000),2),
        'Month_1_Free_Propensity': round(random.random(),2),
        'Month_2_Free_Propensity': round(random.random(),2),
        'Month_3_Free_Propensity': round(random.random(),2),
    }

# Generate 50 random customers
customer_data = [generate_customer() for _ in range(50)]

# Assign CustomerID sequentially from 1 to 50
for index, customer in enumerate(customer_data, start=1):
    customer['CustomerID'] = index
    
# Convert the list of dictionaries to a DataFrame
df_customers = pd.DataFrame(customer_data)

# export
df_customers.to_csv('reactive_input_2.csv', index=False)

In [30]:
df_customers

,Name,Email,Phone,Lapse_Propensity,Customer_Lifetime_Value,Call_Agent,Discount_Eligibility,Age,Tenure,Family_Status,Annual_Premium,Month_1_Free_Propensity,Month_2_Free_Propensity,Month_3_Free_Propensity,CustomerID
0,Paula Hahn,jsanders@example.org,001-401-392-7411x2188,0.11,37117.94,Paula Hahn,eligible,34,2,Family with Multiple Children,8704.17,0.66,0.90,1.00,1
1,Jason Jones,cwhitney@example.com,938.256.5046x2756,0.47,27223.14,Jason Jones,eligible,57,9,Family with Multiple Children,8690.02,0.29,0.56,0.22,2
2,Krista Jones,lisa97@example.com,+1-266-362-4015x73477,0.10,46975.11,Krista Jones,eligible,70,1,Family with Multiple Children,7421.16,0.73,0.82,0.72,3
3,Tracy Barry,kelly08@example.net,001-971-886-7063x6557,0.71,16132.16,Tracy Barry,not eligible,22,19,Single,5502.05,0.01,0.78,0.06,4
4,Matthew Mcclain,ccameron@example.com,978.328.8494x17495,0.27,37685.61,Matthew Mcclain,not eligible,41,19,Family with Multiple Children,6559.11,0.37,0.25,0.87,5
5,Patrick Miller,tcarney@example.org,919-879-7230,0.78,24754.87,Patrick Miller,eligible,30,11,Single parent family,9428.84,0.65,0.46,0.97,6
6,Michael Molina,christophersalazar@example.org,608-675-2518x17275,0.54,39892.40,Michael Molina,eligible,21,3,Single parent family,5324.43,0.64,0.19,0.63,7
7,Matthew Jordan,donald17@example.org,6712419124,0.80,13735.76,Matthew Jordan,eligible,44,15,Family with Multiple Children,7267.99,0.11,0.94,0.59,8
8,Crystal Thomas,karengreen@example.org,1770310649,0.84,20095.46,Crystal Thomas,not eligible,25,18,Single parent family,1289.63,0.96,0.97,0.08,9
9,Stephanie Ray,kelli76@example.net,(057)291-8863,0.15,41877.60,Stephanie Ray,not eligible,48,17,Single,8855.17,0.72,0.72,0.41,10
10,Eric Anderson,john77@example.net,001-367-900-0608,0.53,21769.81,Eric Anderson,not eligible,67,11,Single parent family,9520.65,0.40,0.20,0.59,11
11,Ian Gallegos,jody53@example.org,001-751-621-8781x1609,0.02,8752.96,Ian Gallegos,not eligible,51,18,Family,8103.85,0.01,0.74,0.46,12
12,Eric Cameron,ellisjoshua@example.com,139-082-8180,0.91,41493.17,Eric Cameron,eligible,39,17,Single,7000.41,0.50,0.48,0.71,13
13,Peter Hughes,murphydiane@example.net,001-947-569-0631x3956,0.62,43038.13,Peter Hughes,not eligible,24,18,Single parent family,8152.06,0.63,0.68,0.25,14
14,Dominic Robinson,dhamilton@example.net,+1-734-257-0067,0.98,13875.74,Dominic Robinson,not eligible,35,11,Family,8777.64,0.06,0.58,0.66,15
15,Laurie Waters,richardsantos@example.com,001-277-755-2060x198,0.95,46125.18,Laurie Waters,eligible,65,17,Family with Multiple Children,6264.02,0.01,0.68,0.95,16
16,Kristopher Graham,mcdanieljames@example.org,5130144641,0.66,33990.98,Kristopher Graham,eligible,63,8,Single,8044.71,0.84,0.00,0.77,17
17,Kevin Salinas,barrettmegan@example.com,281.459.7319x1052,0.77,2659.35,Kevin Salinas,not eligible,30,4,Family,5394.26,0.32,0.58,0.19,18
18,Holly Patel,pmorales@example.com,(565)068-4989x18647,0.59,38407.74,Holly Patel,eligible,21,4,Single parent family,6879.32,0.69,0.93,0.42,19
19,Alicia Rich,yangangela@example.com,608.618.1083x771,0.38,46735.32,Alicia Rich,not eligible,56,7,Single parent family,7582.68,0.73,0.88,0.17,20
20,Dr. Beth Woods,jacksonmichael@example.org,(787)855-9715x1633,0.99,7919.69,Dr. Beth Woods,not eligible,43,10,Family with Multiple Children,4784.51,0.13,0.14,0.54,21
21,James Wells,stephanie85@example.net,375-152-7440,0.49,17715.21,James Wells,not eligible,46,1,Family with Multiple Children,3061.24,0.93,0.29,0.98,22
22,Corey Smith,tammy91@example.org,383-718-7737,0.94,27736.84,Corey Smith,eligible,26,5,Couple,7484.67,0.08,0.76,0.36,23
23,Duane Robbins,qlandry@example.net,306.031.3422,0.13,20651.81,Duane Robbins,eligible,49,7,Single parent family,4048.27,0.65,0.57,0.41,24
24,William Davis,snowsandra@example.net,(175)730-6118,0.18,-4279.51,William Davis,eligible,26,13,Family with Multiple Children,1136.68,0.37,0.17,0.66,25
25,Stephen Harrison,ujimenez@example.org,+1-052-696-4485x7802,0.49,3140.85,Stephen Harrison,not eligible,34,19,Couple,2591.47,0.43,0.80,0.25,26
26,Anthony Wright,campbellalexa@example.org,001-531-281-7097,0.08,23488.57,Anthony Wright,not eligible,45,20,Couple,6981.79,0.28,0.48,0.75,27
27,Jean Gray,saramurphy@example.org,001-731-058-8685x24495,0.75,2666.24,Jean Gray,not eligible,58,6,Family,5235.46,0.92,0.89,0.52,28
28,Heidi Olson,amiller@example.com,+1-802-539-4173x0069,0.56,14564.78,Heidi Olson,not eligible,47,1,Family with Multiple Children,8757.25,0.48,0.77,0.83,29
29,Ashley Henson,linda56@example.net,372-493-5772x30054,0.16,32367.20,Ashley Henson,not eligible,69,13,Family with Multiple Children,1103.70,0.24,0.77,0.32,30
30,Donald Boyd,zmacias@example.net,100.454.0640,0.24,26774.53,Donald Boyd,not eligible,34,3,Family with Multiple Children,6185.20,0.54,0.05,0.06,31
31,Vanessa Sanchez,martinvelasquez@example.org,+1-598-751-9572x686,0.93,49148.60,Vanessa Sanchez,not eligible,47,11,Couple,1592.80,0.69,0.04,0.79,32
32,Jennifer Levy,marcuswoods@example.org,454-095-1487,0.68,34397.27,Jennifer Levy,eligible,57,8,Couple,8843.88,0.24,0.13,0.36,33
33,Mrs. Jessica Cooley,miguelball@example.net,326-271-8470x686,0.34,47801.52,Mrs. Jessica Cooley,eligible,47,7,Family with Multiple Children,2687.40,0.57,0.60,0.32,34
34,Emily Beard,gregoryrichards@example.net,(231)068-3298x67983,0.03,46950.69,Emily Beard,eligible,65,14,Couple,5156.95,0.91,0.46,0.34,35
35,Keith Bishop,melindamendez@example.org,354-506-9744x3800,0.43,14901.85,Keith Bishop,not eligible,57,11,Family with Multiple Children,6051.10,0.78,0.21,0.31,36
36,Samantha Johnson,davisstephanie@example.net,165-632-1326,0.30,13200.45,Samantha Johnson,not eligible,33,6,Family with Multiple Children,1588.95,0.20,0.99,0.58,37
37,Lawrence Cooper,esantos@example.com,+1-569-506-0503x5767,0.31,29753.37,Lawrence Cooper,eligible,54,6,Single parent family,6518.52,0.26,0.59,0.46,38
38,Michael Wang,davisgary@example.net,(711)533-6915x015,0.38,18441.37,Michael Wang,eligible,69,13,Single,6659.47,0.89,0.53,0.44,39
39,Kathleen Logan,patrickkeller@example.com,001-751-605-4149x6609,0.01,-1449.10,Kathleen Logan,not eligible,67,9,Family with Multiple Children,7601.14,0.98,0.22,0.38,40
40,Billy Willis,hjones@example.org,001-929-860-5949x50823,0.49,-2549.85,Billy Willis,eligible,28,10,Family with Multiple Children,9716.41,0.16,0.80,0.06,41
41,Tonya Mccarthy,murphyjose@example.com,001-241-304-2753x270,0.00,41834.56,Tonya Mccarthy,not eligible,36,11,Family with Multiple Children,8991.00,0.34,0.05,0.28,42
42,Donna Martin,ashleymoore@example.net,+1-768-387-1086,0.50,22698.76,Donna Martin,not eligible,24,18,Single,9586.17,0.26,0.35,0.51,43
43,Alexandra Hunt,lisa69@example.net,+1-240-780-1746x781,0.01,44900.76,Alexandra Hunt,eligible,57,5,Family with Multiple Children,4328.53,0.91,0.15,0.08,44
44,Lauren Whitaker,vfields@example.com,5322392294,0.57,9233.76,Lauren Whitaker,eligible,46,18,Single,6044.99,0.74,0.06,0.68,45
45,David Wilkerson,brendanyork@example.com,001-495-627-6159,0.66,46835.81,David Wilkerson,eligible,54,13,Couple,8235.99,0.94,0.66,0.20,46
46,Emily Mitchell,wholmes@example.com,142-587-5541x6899,0.56,20440.65,Emily Mitchell,eligible,62,11,Family with Multiple Children,9950.40,0.03,0.05,0.20,47
47,Michael Hanna,sullivanadam@example.org,647.851.2197x8802,0.17,1820.18,Michael Hanna,eligible,43,17,Single parent family,4524.22,0.05,0.32,0.90,48
48,Heather May,allen50@example.net,+1-157-578-7116x77315,0.66,6129.49,Heather May,eligible,66,13,Single parent family,1990.90,0.79,0.01,0.89,49
49,Pamela Bautista,tuckerkathryn@example.net,285-954-4463,0.07,14233.94,Pamela Bautista,eligible,41,18,Couple,1821.36,0.65,0.78,0.86,50