In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('reactive_input.csv')
df.head(3)

,CustomerID,Name,Email,Phone,Lapse_Propensity,Customer_Lifetime_Value,Call_Agent,Discount_Eligibility,Annual_Premium
0,1,John Doe,johndoe@example.com,123-456-7890,0.25,1500,Agent A,eligible,1000
1,2,Jane Smith,janesmith@example.com,987-654-3210,0.35,1200,Agent B,eligible,1100
2,3,Alice Johnson,alicejohnson@example.com,456-789-0123,0.15,800,Agent C,not eligible,1050

In [25]:
from faker import Faker
import random
import pandas as pd

# Initialize Faker
fake = Faker()

def generate_customer():
    name = fake.name()
    email = fake.email()
    phone_number = fake.phone_number()
    return {
        'Name': name,
        'Email': email,
        'Phone': phone_number,
        'Lapse_Propensity': round(random.random(),2),
        'Customer_Lifetime_Value': round(random.uniform(-5000, 50000),2),
        'Call_Agent': name,
        'Discount_Eligibility': random.choice(['eligibile', 'not eligible']),
        'Age': random.randint(18, 70),
        'Tenure': random.randint(1, 20),
        'Family_Status': random.choice(['Single', 'Couple', 'Single parent family', 'Family', 'Family with Multiple Children']),
        'Annual_Premium': round(random.uniform(1000, 10000),2),
        'Month_1_Free_Propensity': round(random.random(),2),
        'Month_2_Free_Propensity': round(random.random(),2),
        'Month_3_Free_Propensity': round(random.random(),2),
    }

# Generate 50 random customers
customer_data = [generate_customer() for _ in range(50)]

# Assign CustomerID sequentially from 1 to 50
for index, customer in enumerate(customer_data, start=1):
    customer['CustomerID'] = index
    
# Convert the list of dictionaries to a DataFrame
df_customers = pd.DataFrame(customer_data)

# export
df_customers.to_csv('reactive_input_2.csv', index=False)

In [26]:
df_customers

,Name,Email,Phone,Lapse_Propensity,Customer_Lifetime_Value,Call_Agent,Discount_Eligibility,Age,Tenure,Family_Status,Annual_Premium,Month_1_Free_Propensity,Month_2_Free_Propensity,Month_3_Free_Propensity,CustomerID
0,Chad Ramos,hillcarrie@example.org,+1-275-965-7123,0.92,22914.18,Chad Ramos,eligibile,66,16,Couple,7002.48,0.43,0.22,0.96,1
1,Lindsey Richardson,julie50@example.com,076.016.8402,0.02,10569.34,Lindsey Richardson,not eligible,28,15,Family,9379.46,0.65,0.95,0.64,2
2,Robert Peterson,robertstimothy@example.net,033-124-1267,0.59,40658.67,Robert Peterson,not eligible,51,17,Single,6155.69,0.42,0.52,0.83,3
3,Pamela Mccoy,obrown@example.org,+1-602-884-7277,0.27,48459.03,Pamela Mccoy,eligibile,28,6,Family with Multiple Children,9420.55,0.21,0.57,0.12,4
4,Eugene Robinson,ahendricks@example.org,428.422.8500x995,0.78,44606.56,Eugene Robinson,eligibile,45,7,Single,8385.91,0.28,0.27,0.88,5
5,Joshua King,zstout@example.org,901.521.7664x067,0.85,20512.69,Joshua King,eligibile,53,1,Family,6582.38,0.03,0.08,0.10,6
6,Benjamin Obrien,brandon70@example.net,947.117.8359x936,0.01,36463.54,Benjamin Obrien,eligibile,32,1,Family,3152.86,0.87,0.24,0.36,7
7,Sandy Logan,rossmelissa@example.net,8300643982,0.59,16388.40,Sandy Logan,eligibile,48,20,Single,1688.21,0.06,0.80,0.40,8
8,Tammie Garcia,guerramary@example.com,1381459230,0.41,16361.37,Tammie Garcia,eligibile,38,10,Single parent family,6709.62,0.01,0.27,0.32,9
9,Kyle Allen,yjones@example.org,(157)401-7753x392,0.87,10213.72,Kyle Allen,not eligible,65,15,Single parent family,6513.68,0.18,0.11,0.60,10
10,Megan Howard,haroldmorris@example.org,793-155-6868,0.71,8127.81,Megan Howard,eligibile,64,1,Single parent family,9473.58,0.86,0.80,0.89,11
11,Justin Petersen,nmercer@example.com,917-276-8026x62376,0.36,1641.87,Justin Petersen,not eligible,67,6,Single parent family,2316.87,0.68,0.67,0.54,12
12,Matthew Stark,adrianhamilton@example.net,(023)038-1656,0.71,4900.29,Matthew Stark,eligibile,60,6,Single,9970.23,0.82,0.33,0.80,13
13,Shaun Joseph,armstrongbrooke@example.net,001-468-066-1622,0.13,-4754.74,Shaun Joseph,not eligible,60,15,Single,5522.14,0.52,0.66,0.89,14
14,Edward Duncan,vincent46@example.com,517-999-7110x68894,0.33,39942.82,Edward Duncan,eligibile,57,9,Single,5084.87,0.55,0.31,0.58,15
15,Melissa Green,kaitlyn06@example.org,193-794-4179x8694,0.14,48787.15,Melissa Green,eligibile,40,12,Family,1194.64,0.52,0.50,0.56,16
16,Kevin Jones,jocelyncunningham@example.net,993.787.4542,0.97,18360.87,Kevin Jones,eligibile,57,8,Single parent family,6807.96,0.96,1.00,0.53,17
17,Ann Perkins,jessicapham@example.org,467.400.0689x8562,0.31,2749.97,Ann Perkins,eligibile,44,14,Single parent family,4128.42,0.26,0.86,0.97,18
18,Jennifer Turner,kyle53@example.com,(987)782-7218x62991,0.50,17167.69,Jennifer Turner,eligibile,69,10,Single parent family,7050.05,0.34,0.74,0.96,19
19,Alexis Johnson,bryanbowman@example.net,896-349-3222,0.35,22006.13,Alexis Johnson,eligibile,48,16,Single parent family,5391.58,0.24,0.26,0.93,20
20,Scott Kelley,jrivera@example.com,6274167046,0.02,17737.12,Scott Kelley,eligibile,70,2,Family,2345.99,0.37,0.27,0.95,21
21,Jessica Tran,daughertyrandall@example.net,(102)235-2087x63861,0.62,29430.42,Jessica Tran,not eligible,52,3,Couple,4045.14,0.80,0.29,0.93,22
22,Michael Wong,nicholasperry@example.net,834.108.4768,0.16,44970.11,Michael Wong,eligibile,57,3,Single,1483.67,0.80,0.18,0.35,23
23,Cassandra Bryant MD,iwilliams@example.com,488.926.4029x874,0.57,8552.46,Cassandra Bryant MD,not eligible,20,10,Single,8006.01,0.77,0.96,0.43,24
24,Brian Cox,michael28@example.net,035-562-6033x3913,0.73,-2317.94,Brian Cox,not eligible,34,9,Single parent family,1199.37,0.53,0.35,0.46,25
25,Martin Jordan,vmartinez@example.org,362-283-9411x5106,0.77,34251.99,Martin Jordan,eligibile,47,10,Single,7503.84,0.04,0.22,0.89,26
26,Jonathan Lee,richarddavis@example.com,0045555409,0.13,-2070.42,Jonathan Lee,eligibile,32,11,Single parent family,3282.79,0.17,0.61,0.71,27
27,Alejandro Rogers,linjames@example.net,315.413.4381x1503,0.67,35532.84,Alejandro Rogers,not eligible,44,8,Single parent family,9109.67,0.81,0.73,0.61,28
28,Randy Bates,amyjefferson@example.com,+1-561-783-7705x52017,0.10,-3523.97,Randy Bates,not eligible,69,3,Single,8314.28,0.63,0.11,0.18,29
29,Matthew Cherry,dawn68@example.com,166-703-7501x9204,0.02,5540.93,Matthew Cherry,eligibile,63,4,Single parent family,4123.36,0.33,0.10,0.82,30
30,Debbie Mcgrath,xaguilar@example.com,008-043-8804x07127,0.40,28805.91,Debbie Mcgrath,not eligible,65,5,Family with Multiple Children,6501.13,0.16,0.73,0.97,31
31,Jenna Blair,guzmanthomas@example.com,799.461.1713x3230,0.52,6728.21,Jenna Blair,not eligible,41,3,Family,9129.60,0.15,0.27,0.96,32
32,Ryan Brown,nmathews@example.org,377-573-2098x6199,0.68,22696.47,Ryan Brown,eligibile,32,7,Family with Multiple Children,8180.61,0.73,0.39,0.24,33
33,Felicia Clark,tylerlong@example.net,(885)238-2344x2035,0.84,24380.01,Felicia Clark,eligibile,46,2,Single parent family,3137.14,0.25,0.68,0.41,34
34,Caroline Arnold,jocelyn68@example.net,+1-233-284-3510x89727,0.24,11858.69,Caroline Arnold,eligibile,66,9,Family with Multiple Children,5767.32,0.66,0.77,0.53,35
35,John Lewis,gloriabird@example.com,(474)384-6074,0.91,22411.25,John Lewis,not eligible,57,11,Single parent family,2557.36,0.27,0.08,0.52,36
36,Natasha Perez MD,lawrence75@example.com,261.726.5481,0.01,47061.73,Natasha Perez MD,eligibile,32,13,Couple,5735.94,0.54,0.30,0.22,37
37,Rick Johnson,garretttina@example.com,+1-945-998-9366x85360,0.08,-197.99,Rick Johnson,eligibile,49,15,Single,4299.12,0.17,0.70,0.15,38
38,Michael Ramirez,amandagraves@example.net,9589769893,0.20,8112.20,Michael Ramirez,eligibile,58,15,Single parent family,6782.77,0.44,0.46,0.82,39
39,Christine Parsons,guerreroheather@example.net,001-448-939-8832x188,0.70,5094.58,Christine Parsons,eligibile,53,4,Single,9926.92,0.13,0.12,0.68,40
40,Lisa Carroll,tgeorge@example.com,(032)630-8705,0.36,13441.32,Lisa Carroll,not eligible,66,11,Couple,7288.81,0.78,0.73,0.26,41
41,Sarah Cline,erik01@example.org,(388)248-4635,0.11,32513.62,Sarah Cline,not eligible,24,13,Single,4335.68,0.22,0.70,0.81,42
42,Kristen Gentry,icox@example.org,001-245-400-7344x6611,0.75,369.10,Kristen Gentry,eligibile,19,20,Family,4960.75,0.11,0.99,0.55,43
43,Jeremy Simmons,courtney47@example.net,699.756.1829x4087,0.92,47837.66,Jeremy Simmons,eligibile,57,13,Single,1583.53,0.66,0.32,0.42,44
44,Jared Sellers,katherineadams@example.org,554.602.3116x49871,0.29,27229.30,Jared Sellers,not eligible,26,4,Single parent family,7408.58,0.60,0.50,0.12,45
45,Victor Welch,kimberly94@example.net,235.242.8925,0.53,42523.37,Victor Welch,eligibile,41,8,Single,4649.35,0.02,0.28,0.89,46
46,John Vargas,wardkimberly@example.org,001-824-388-0229x81763,0.84,2842.57,John Vargas,eligibile,21,9,Family with Multiple Children,4183.62,0.42,0.02,0.70,47
47,Laura Ortiz,mwashington@example.org,+1-834-010-3164x9125,0.17,38236.52,Laura Ortiz,eligibile,19,11,Family with Multiple Children,7215.81,0.44,0.55,0.77,48
48,Emily Walker,dsosa@example.com,(752)345-6959x23821,0.90,28121.81,Emily Walker,eligibile,36,6,Family with Multiple Children,9741.53,0.42,0.84,0.27,49
49,Michael Lewis,kevin68@example.net,+1-633-917-9196x0901,0.44,31900.58,Michael Lewis,eligibile,70,9,Single,4849.84,0.62,0.35,0.02,50